version: "3"
services:
  algorithms-list:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: algorithms-list
    volumes:
      - .:/opt/algorithms-list/app/
    tty: true
